# Generated by Django 3.2 on 2021-04-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice1',
        ),
    ]
