# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0002_auto_20210425_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
